# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 19:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=30)),
                ('syntax', models.CharField(choices=[('plain', 'Plain'), ('python', 'Python'), ('html', 'HTML'), ('sql', 'SQL'), ('javascript', 'Javascript'), ('css', 'CSS')], default='plain', max_length=50)),
                ('createDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expiryDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paste_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createDate',),
            },
        ),
    ]
