# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20171124_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.CharField(choices=[('plain', 'Plain'), ('python', 'Python'), ('html', 'HTML'), ('sql', 'SQL'), ('javascript', 'Javascript'), ('css', 'CSS')], default='plain', max_length=50),
        ),
    ]
