# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_auto_20171124_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='poster',
        ),
    ]
